### ISSUE TITLE
Which is the right pyglm plugin?

### ISSUE THREAD

**Issue by sven-mayer** [imldresden/GIAnT#2]
My installation is failing when including player.loadPlugin("pyglm") in https://github.com/imldresden/GIAnT/blob/master/pat_model.py  line 24

I do guess I am missing a plugin for the libavg named pyglm. Can you point me to the right plugin?

**Comment by uzadow** [comment]
Hi Sven,

PyGLM is a tiny library that we use internally, and it seems we missed that dependency when we uploaded GIAnT to github. Sorry! I'll try to upload PyGLM today or tomorrow.

Cheers,

  Uli

**Comment by uzadow** [comment]
Hi again, I've published PyGLM and updated GIAnT's readme file.

PyGLM is here: https://github.com/imldresden/PyGLM

If you run into any more issues, don't hesitate to ask!

**Comment by sven-mayer** [comment]
First of all thanks for the hotfix.

Over the course of the installation, actually this other plugin is required:
player.loadPlugin("plots")

and I double checked there is another one down the installation:
player.loadPlugin("heatmap")

I hope you can help me with the two other plugins as well.

**Comment by uzadow** [comment]
Hi, sorry about this!

I've uploaded HeatMapNode as well and updated GIAnT's readme. plots should have been available already - it is part of the GIAnT package and installation is described under "The libavg plugin".

Leaving this closed, but don't hesitate to re-open in case there are other install issues.
