### ISSUE TITLE
Rotaion in Optitrack Data

### ISSUE THREAD

**Issue by sven-mayer** [imldresden/GIAnT#6]
in the README is described that "rot" is an (a,b,c,d) quaternion, however, in the example code, this coded as a 3-tuple. I'm wondering what's correct. If its a 3-tuple then I guess its angle in rad? If so, how can you ensure the flip in the rotation? That's why people use quaternion. 

Further, I tried loading a 4-tuple which didn't work for me. The tool only loads 3-tuple.

**Comment by uzadow** [comment]
You're right, the angle is a 3-component Euler angle, and the readme is incorrect.

It would probably have been better to store it as a quat, but there's no real problem. Calculations on 3D rotations are done in quaternion space like they should be (see, e.g., pat_model.py, lines 120ff, which calculates the viewpoint at the wall).

I've updated the readme to specify the angles clearly.
